---
- name: pass
  hosts: localhost
  vars:
    greeting: "{{ ansible_all_ipv4_addresses }}"
    #greeting: "you didn't "
  tasks:
    - name: output a message
      debug: msg="{{ greeting }}"
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="{{ login.stdout }}"
