---
- name: test
  hosts: test
  tasks:
    - name: date
      command: date
      register: d
    - debug: msg="{{d }}"
- name: pass
  hosts: localhost
  vars:
    greeting: "{{ ansible_all_ipv4_addresses }}"
    #greeting: "you didn't "
    from: "camelot"
    # from: "some password"
  vars_prompt:
    - name: "camelot"
      prompt: "enter password"
      private: no
      # private: yes
  tasks:
    - name: output a message
      debug: msg="{{ greeting }}"
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="{{ login.stdout }}"
    - debug: msg="{{ camelot }}"
